In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

matches = pd.read_csv("../data/raw/matches.csv")
deliveries = pd.read_csv("../data/raw/deliveries.csv")

In [2]:
import os
print(os.getcwd())

a:\projects\AIML-projects\IPL-Analytics-Pipeline\notebooks

In [3]:
print(os.listdir(".."))

['.git', '.gitignore', '.venv', 'dashboard', 'data', 'images', 'main.py', 'notebooks', 'pipeline', 'README.md', 'reports', 'requirements.txt', 'sql']

In [4]:
print(os.listdir("../pipeline"))

['analytics.py', 'clean.py', 'database.py', 'extract.py', 'load.py', 'transform.py', '__init__.py', '__pycache__']

In [5]:
import sys
import os

PROJECT_ROOT = os.path.abspath("..")
sys.path.insert(0, PROJECT_ROOT)

from pipeline.extract import load_matches, load_deliveries

matches = load_matches("../data/raw/matches.csv")
deliveries = load_deliveries("../data/raw/deliveries.csv")

In [6]:
matches.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [7]:
deliveries.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [8]:
matches.info()

<class 'pandas.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   str
 2   city             1044 non-null   str
 3   date             1095 non-null   str
 4   match_type       1095 non-null   str
 5   player_of_match  1090 non-null   str
 6   venue            1095 non-null   str
 7   team1            1095 non-null   str
 8   team2            1095 non-null   str
 9   toss_winner      1095 non-null   str
 10  toss_decision    1095 non-null   str
 11  winner           1090 non-null   str
 12  result           1095 non-null   str
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   str
 17  method           21 non-null     str
 18  umpire1          1095 non-null   str
 19  umpire2          1095 non-null   str
dtypes: float64(3), int64(1), str(16)
memory usage: 352.4 KB

In [9]:
deliveries.info()

<class 'pandas.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   inning            260920 non-null  int64
 2   batting_team      260920 non-null  str
 3   bowling_team      260920 non-null  str
 4   over              260920 non-null  int64
 5   ball              260920 non-null  int64
 6   batter            260920 non-null  str
 7   bowler            260920 non-null  str
 8   non_striker       260920 non-null  str
 9   batsman_runs      260920 non-null  int64
 10  extra_runs        260920 non-null  int64
 11  total_runs        260920 non-null  int64
 12  extras_type       14125 non-null   str
 13  is_wicket         260920 non-null  int64
 14  player_dismissed  12950 non-null   str
 15  dismissal_kind    12950 non-null   str
 16  fielder           9354 non-null    str
dtypes: int64(8), str(9)
memory usage: 50.4 MB

In [10]:
matches.isnull().sum()

id                    0
season                0
city                 51
date                  0
match_type            0
player_of_match       5
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                5
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

In [11]:
deliveries.isnull().sum()

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type         246795
is_wicket                0
player_dismissed    247970
dismissal_kind      247970
fielder             251566
dtype: int64

In [12]:
matches.shape

(1095, 20)

In [13]:
deliveries.shape

(260920, 17)

In [14]:
from pipeline.clean import (
    remove_duplicates,
    missing_value_report,
    standardize_column_names
)

In [15]:
matches.duplicated().sum()

np.int64(0)

In [16]:
deliveries.duplicated().sum()

np.int64(0)

In [17]:
matches = remove_duplicates(matches)
deliveries = remove_duplicates(deliveries)

In [18]:
missing_value_report(matches)

                 Missing Values  Percentage
method                     1074       98.08
city                         51        4.66
result_margin                19        1.74
player_of_match               5        0.46
winner                        5        0.46
target_runs                   3        0.27
target_overs                  3        0.27
id                            0        0.00
date                          0        0.00
season                        0        0.00
venue                         0        0.00
match_type                    0        0.00
toss_decision                 0        0.00
toss_winner                   0        0.00
team2                         0        0.00
team1                         0        0.00
result                        0        0.00
super_over                    0        0.00
umpire1                       0        0.00
umpire2                       0        0.00

In [19]:
missing_value_report(deliveries)

                  Missing Values  Percentage
fielder                   251566       96.41
dismissal_kind            247970       95.04
player_dismissed          247970       95.04
extras_type               246795       94.59
match_id                       0        0.00
inning                         0        0.00
batting_team                   0        0.00
bowling_team                   0        0.00
over                           0        0.00
non_striker                    0        0.00
bowler                         0        0.00
batter                         0        0.00
ball                           0        0.00
total_runs                     0        0.00
extra_runs                     0        0.00
batsman_runs                   0        0.00
is_wicket                      0        0.00

In [20]:
matches = standardize_column_names(matches)
deliveries = standardize_column_names(deliveries)

print(matches.columns)

Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='str')

In [21]:
from pipeline.transform import (
    convert_dates,
    extract_year,
    fill_missing_city
)

In [22]:
matches = convert_dates(matches)

In [23]:
matches.info()

<class 'pandas.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   str
 2   city             1044 non-null   str
 3   date             1095 non-null   datetime64[us]
 4   match_type       1095 non-null   str
 5   player_of_match  1090 non-null   str
 6   venue            1095 non-null   str
 7   team1            1095 non-null   str
 8   team2            1095 non-null   str
 9   toss_winner      1095 non-null   str
 10  toss_decision    1095 non-null   str
 11  winner           1090 non-null   str
 12  result           1095 non-null   str
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   str
 17  method           21 non-null     str
 18  umpire1          1095 non-null   str
 19  umpire2          1095 non-null   str
dtypes: datetime64[us](1), float64(3), int64(1), str(15)
memory usage: 341.7 KB

In [24]:
matches = extract_year(matches)

In [25]:
matches.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2,season_year
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,2008
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,...,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri,2008
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,...,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar,2008
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,...,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper,2008
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,...,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan,2008

In [26]:
matches = fill_missing_city(matches)

In [27]:
matches["city"].isnull().sum()

np.int64(0)

In [28]:
matches.info()

matches.head()

matches["city"].isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   str
 2   city             1095 non-null   str
 3   date             1095 non-null   datetime64[us]
 4   match_type       1095 non-null   str
 5   player_of_match  1090 non-null   str
 6   venue            1095 non-null   str
 7   team1            1095 non-null   str
 8   team2            1095 non-null   str
 9   toss_winner      1095 non-null   str
 10  toss_decision    1095 non-null   str
 11  winner           1090 non-null   str
 12  result           1095 non-null   str
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   str
 17  method           21 non-null     str
 18  umpire1          1095 non-null   str
 19  umpire2          1095 non-null   str
 20  season_year      1095 non-null   int32
dtypes: datetime64[us](1), float64(3), int32(1), int64(1), str(15)
memory usage: 346.2 KB

np.int64(0)

In [29]:
from pipeline.analytics import team_win_percentage

In [30]:
team_stats = team_win_percentage(matches)

team_stats

                             Matches Played  Matches Won  Win Percentage
Rising Pune Supergiant                   16           10           62.50
Gujarat Titans                           45           28           62.22
Chennai Super Kings                     237          138           58.23
Lucknow Super Giants                     43           24           55.81
Mumbai Indians                          261          144           55.17
Delhi Capitals                           91           48           52.75
Kolkata Knight Riders                   251          131           52.19
Rajasthan Royals                        219          112           51.14
Royal Challengers Bangalore             237          116           48.95
Sunrisers Hyderabad                     182           88           48.35
Royal Challengers Bengaluru              15            7           46.67
Kings XI Punjab                         190           88           46.32
Gujarat Lions                            30           13           43.33
Punjab Kings                             56           24           42.86
Kochi Tuskers Kerala                     14            6           42.86
Delhi Daredevils                        159           67           42.14
Deccan Chargers                          75           29           38.67
Rising Pune Supergiants                  14            5           35.71
Pune Warriors                            45           12           26.67

In [31]:
def top_teams_by_wins(matches):
    """
    Return teams sorted by total wins.
    """

    return (
        matches["winner"]
        .value_counts()
        .reset_index()
        .rename(columns={
            "index":"Team",
            "winner":"Wins"
        })
    )

In [32]:
top_teams_by_wins(matches)

                           Wins  count
0                Mumbai Indians    144
1           Chennai Super Kings    138
2         Kolkata Knight Riders    131
3   Royal Challengers Bangalore    116
4              Rajasthan Royals    112
5               Kings XI Punjab     88
6           Sunrisers Hyderabad     88
7              Delhi Daredevils     67
8                Delhi Capitals     48
9               Deccan Chargers     29
10               Gujarat Titans     28
11                 Punjab Kings     24
12         Lucknow Super Giants     24
13                Gujarat Lions     13
14                Pune Warriors     12
15       Rising Pune Supergiant     10
16  Royal Challengers Bengaluru      7
17         Kochi Tuskers Kerala      6
18      Rising Pune Supergiants      5

In [33]:
def toss_analysis(matches):
    """
    Analyze toss winners and decisions.
    """

    return pd.crosstab(
        matches["toss_decision"],
        matches["winner"] == matches["toss_winner"]
    )

In [34]:
toss_analysis(matches)

col_0          False  True
toss_decision
bat              214    177
field            327    377

In [35]:
import sys
import os

PROJECT_ROOT = os.path.abspath("..")
sys.path.insert(0, PROJECT_ROOT)

print(PROJECT_ROOT)

a:\projects\AIML-projects\IPL-Analytics-Pipeline

In [36]:
from pipeline.analytics import (
    top_run_scorers,
    top_wicket_takers,
    most_sixes,
    most_fours
)

In [37]:
from pipeline.extract import load_matches, load_deliveries

matches = load_matches("../data/raw/matches.csv")
deliveries = load_deliveries("../data/raw/deliveries.csv")

In [38]:
top_run_scorers(deliveries)

           Batter  Runs
0         V Kohli  8014
1        S Dhawan  6769
2       RG Sharma  6630
3       DA Warner  6567
4        SK Raina  5536
5        MS Dhoni  5243
6  AB de Villiers  5181
7        CH Gayle  4997
8      RV Uthappa  4954
9      KD Karthik  4843

In [39]:
top_wicket_takers(deliveries)

       bowler  Wickets
0   YS Chahal      213
1    DJ Bravo      207
2   PP Chawla      201
3   SP Narine      200
4    R Ashwin      198
5     B Kumar      195
6  SL Malinga      188
7    A Mishra      183
8   JJ Bumrah      182
9   RA Jadeja      169

In [40]:
most_sixes(deliveries)

           batter  Sixes
0        CH Gayle    359
1       RG Sharma    281
2         V Kohli    273
3  AB de Villiers    253
4        MS Dhoni    252
5       DA Warner    236
6      KA Pollard    224
7      AD Russell    209
8       SV Samson    206
9        SK Raina    204

In [41]:
from pipeline.analytics import strike_rate

strike_rate(deliveries)

              batter  Runs  Balls  Strike Rate
0    J Fraser-McGurk   330    150       220.00
1           WG Jacks   230    133       172.93
2            PD Salt   653    385       169.61
3           T Stubbs   405    239       169.46
4            TM Head   772    458       168.56
..               ...   ...    ...          ...
295           Z Khan   117    141        82.98
296      CJ Ferguson    98    119        82.35
297    Kuldeep Yadav   183    224        81.70
298         IR Jaggi    76    100        76.00
299       RT Ponting    91    129        70.54

[300 rows x 4 columns]

In [42]:
from pipeline.analytics import toss_decision_percentage

toss_decision_percentage(matches)

  Decision  Percentage
0    field       64.29
1      bat       35.71

In [43]:
from pipeline.load import save_csv

In [44]:
save_csv(matches, "matches_cleaned.csv")
save_csv(deliveries, "deliveries_cleaned.csv")

Saved: a:\projects\AIML-projects\IPL-Analytics-Pipeline\data/cleaned\matches_cleaned.csv
Saved: a:\projects\AIML-projects\IPL-Analytics-Pipeline\data/cleaned\deliveries_cleaned.csv

In [45]:
import os

print(os.getcwd())

a:\projects\AIML-projects\IPL-Analytics-Pipeline\notebooks

In [46]:
import os

print(os.path.abspath("data/cleaned"))

a:\projects\AIML-projects\IPL-Analytics-Pipeline\notebooks\data\cleaned

In [47]:
save_csv(matches, "matches_cleaned.csv")

Saved: a:\projects\AIML-projects\IPL-Analytics-Pipeline\data/cleaned\matches_cleaned.csv

In [48]:
from pipeline.database import save_to_database

In [50]:
from pipeline.analytics import (
    team_win_percentage,
    top_run_scorers,
    top_wicket_takers,
    venue_statistics,
)

In [51]:
team_stats = team_win_percentage(matches)

runs = top_run_scorers(deliveries)

wickets = top_wicket_takers(deliveries)

venues = venue_statistics(matches)

In [52]:
save_to_database(matches, "matches")
save_to_database(deliveries, "deliveries")
save_to_database(team_stats, "team_statistics")
save_to_database(runs, "top_run_scorers")

matches saved successfully.
deliveries saved successfully.
team_statistics saved successfully.
top_run_scorers saved successfully.

In [55]:
import importlib
import pipeline.database

importlib.reload(pipeline.database)

In [56]:
from pipeline.database import read_table

read_table("top_run_scorers").head()

      Batter  Runs
0    V Kohli  8014
1   S Dhawan  6769
2  RG Sharma  6630
3  DA Warner  6567
4   SK Raina  5536

In [57]:
from pipeline.sql_queries import run_query

In [58]:
query = """
SELECT winner,
COUNT(*) AS Wins
FROM matches
WHERE winner IS NOT NULL
GROUP BY winner
ORDER BY Wins DESC;
"""

run_query(query)

                         winner  Wins
0                Mumbai Indians   144
1           Chennai Super Kings   138
2         Kolkata Knight Riders   131
3   Royal Challengers Bangalore   116
4              Rajasthan Royals   112
5           Sunrisers Hyderabad    88
6               Kings XI Punjab    88
7              Delhi Daredevils    67
8                Delhi Capitals    48
9               Deccan Chargers    29
10               Gujarat Titans    28
11                 Punjab Kings    24
12         Lucknow Super Giants    24
13                Gujarat Lions    13
14                Pune Warriors    12
15       Rising Pune Supergiant    10
16  Royal Challengers Bengaluru     7
17         Kochi Tuskers Kerala     6
18      Rising Pune Supergiants     5